### ISSUE TITLE
After restart All the settings cleared

### ISSUE THREAD

**Issue by javastud** [flaviostutz/freepbx#12]
Hi.
Installed and set up the settings. It was working. Then tried to restart the container. All of my settings was cleared.

Am i doing something wrong? Or is there a problem?

**Comment by flaviostutz** [comment]
A simple restart wouldn’t cause this problem. If the container instance was re-created, it was supposed to restore the last configuration from backup volume.

Have you used volumes as in the example on readme?

**Comment by javastud** [comment]
Hi.
There is no mysql volume definition in Readme, i realized while inspecting Dockerfile. But after i mount the volume mysql doesnt start.

Starting container:
docker run -dit --restart unless-stopped --name freepbx1 -p 16531:80 -p 16532:5060 -p 16533:5160 -p 16565-16600:18000-18035/udp \
--dns=8.8.8.8 \
-v /opt/disk/freepbx/data:/var/lib/mysql \
-v /opt/disk/freepbx/backup:/backup \
-v /opt/disk/freepbx/recordings:/var/spool/asterisk/monitor \
flaviostutz/freepbx:latest

Log:
+ /etc/init.d/mysql start
[....] Starting MySQL database server: mysqld . . . . . . . . . .+ /etc/init.d/mysql start
[FAIL] Starting MySQL database server: mysqld . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . failed!
+ status=1
+ '[' 1 -ne 0 ']'
+ echo 'Failed to start mysql: 1'
Failed to start mysql: 1
+ exit 1
+ /etc/init.d/mysql start
[FAIL] Starting MySQL database server: mysqld . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . failed!
+ status=1
+ '[' 1 -ne 0 ']'
+ echo 'Failed to start mysql: 1'
Failed to start mysql: 1
+ exit 1
+ /etc/init.d/mysql start
[FAIL] Starting MySQL database server: mysqld . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . failed!
+ status=1

**Comment by flaviostutz** [comment]
There is a problem mounting the sql volume, that’s why I created an automatic backup with the volume on readme example.
When you create a new container instance and it finds an existing backup on the mounted volume, it restores it during initialization.

**Comment by flaviostutz** [comment]
Did this fixed your problem?

**Comment by flaviostutz** [comment]
@javastud feel free to reopen this if the problem is still happening, ok?
