### ISSUE TITLE
CDR records not shown

### ISSUE THREAD

**Issue by BoeserBrot** [flaviostutz/freepbx#13]
Hi, thank you for creating this useful docker image, I am using your image since FreePBX14.

However I setup the latest FreePBX15 with all my phones working, but I don't get any CDR records shown. The mariaDB process is running without problems.

Inside the container is the file /etc/asterisk/cdr_adaptive_odbc.conf which I suppose is responsible for connecting FreePBX with mariaDB. The contents of the file are:
[asteriskcdrdb]
connection=asteriskcdrdb
loguniqueid=yes
table=cdr
alias start => calldate

In case you need any more info, please tell me. Thank you for help, it's greatly appreciated.

**Comment by flaviostutz** [comment]
Hi! Glad this image is useful to you!
Have you upgraded from 14 to 15? The SIP trunks and extensions are working well?

**Comment by flaviostutz** [comment]
Sorry, now I saw your extensions are working.
Have you tried to instantiate a fresh FreePBX with no importing of data?

**Comment by BoeserBrot** [comment]
Yes, I setup a fully new container with the latest image and with the docker-compose instructions in the readme. Then I manually made all the settings for my trunks and extensions to work.
Apart from the CDR everything is working well. I looked into the database as well and the asteriskcddrdb is there, but without any entries in the cdr table. Could it possibly be a connection error related to ODBC?

**Comment by flaviostutz** [comment]
Oops, I will have to test it locally too :)

**Comment by RomanUpworksTeam** [comment]
Hi All
I faced the same issue

**Comment by flaviostutz** [comment]
@RomanUpworksTeam, thanks for the tips. I've just added this command to a newer image and you can access it at
flaviostutz/freepbx:15.0.16.8

**Comment by iammenotyou** [comment]
@RomanUpworksTeam did you perform any other changes?  I've tried using image 15.0.16.8 and running `apt install libodbc1 odbcinst odbcinst1debian2` and still CDR is empty.

**Comment by RomanUpworksTeam** [comment]
> @RomanUpworksTeam did you perform any other changes? I've tried using image 15.0.16.8 and running `apt install libodbc1 odbcinst odbcinst1debian2` and still CDR is empty.

Hi. It seems to me that yes... You may need to restart the container

**Comment by iammenotyou** [comment]
@RomanUpworksTeam thanks for the assistance!   Yes, it required the restart before the CDR worked again.

@flaviostutz Thanks for all the hard work on this image.   I really wanted to move fpbx from a virtual machine to docker.  Thanks!
