### ISSUE TITLE
g729 codec issue

### ISSUE THREAD

**Issue by augustodinizl** [flaviostutz/freepbx#15]
Dude, first of all, congratulations for your awesome work!!!

Second, i'm having some troubles for install g729 codec in your docker image, can you give me some guidances?

Third... PARABÉNS!!!! e MUITO SUCESSO!!!!

**Comment by flaviostutz** [comment]
Thanks!
What's happening? Could you please send some logs?

**Comment by augustodinizl** [comment]
I have deleted the instance, i was having some issues to forward some custom ports that my ISP requires, maybe in the next weekend i'll try to setup it again...

**Comment by flaviostutz** [comment]
Great. I've been using g279 with success here. Maybe it is due to the port changes. Are you using network mode host?
