### ISSUE TITLE
Backup cannot be restored

### ISSUE THREAD

**Issue by RomanUpworksTeam** [flaviostutz/freepbx#16]
restoring from userman [FreePBX\modules\Userman\Restore]
Cleaning table: userman_users
"An exception occurred while executing 'INSERT INTO userman_users (`id`, `auth`, `authid`, `username`, `description`, `password`, `default_extension`, `primary_group`, `permissions`, `fname`, `lname`, `displayname`, `title`, `company`, `department`, `language`, `timezone`, `dateformat`, `timeformat`, `datetimeformat`, `email`, `cell`, `work`, `home`, `fax`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["1", "1", "", "300", "Autogenerated user on new device creation", "$2a$08$1xBmhfQBPSNs5hhHGjGqMOooCe8JzjFWVMwygy81pv8qgJBzvrmY.", "300", "", "", "", "", "300", "", "", "", "", "", "", "", "", "", "", "", "", ""]:
"
"SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: '' for column `asterisk`.`userman_users`.`primary_group` at row 1"

**Comment by flaviostutz** [comment]
Are you restoring the backup to the same container instance that created it? FreePbX is very sensible on that matters...

**Comment by flaviostutz** [comment]
@RomanUpworksTeam Feel free to reopen if needing more assistance...
