### ISSUE TITLE
Freepbx New ver. Need AllowOverride All

### ISSUE THREAD

**Issue by sumonchai** [flaviostutz/freepbx#17]
I'm run command 
sed -i '/<Directory \/var\/www\/>/,/<\/Directory>/ s/AllowOverride None/AllowOverride All/' /etc/apache2/apache2.conf

Freepbx fixed.

**Comment by flaviostutz** [comment]
Which version of FreePbX did you tested this fix against?

**Comment by flaviostutz** [comment]
I will work on that today...

Duplicate of #14.

**Comment by flaviostutz** [comment]
Please the latest image with this code snippet you sent at flaviostutz/freepbx:15.0.16.8
