### ISSUE TITLE
Calls drop after 6 seconds

### ISSUE THREAD

**Issue by n8acl** [flaviostutz/freepbx#22]
Hello!

Pretty sure it's a nat issue, but I can't figure out where...

I am spinning this up on Docker CE Version 20.10.7 on Ubuntu Server 20.04.2 LTS with docker-compose version 1.29.2.

I copied the example docker-compose in the readme and made minor tweaks to fit my system:

version: '3.3'
services:
  freepbx:
    image: flaviostutz/freepbx:latest
    container_name: freepbx
    ports:
      - 8080:80
      - 5060:5060/udp
      - 5160:5160/udp
      - 3307:3306 
      - 18000-18100:18000-18100/udp
    restart: always
    environment:
      - ADMIN_PASSWORD=admin1234
      - USE_CHAN_SIP=true
      - FAIL2BAN_ENABLE=false
      - ENABLE_AUTO_RESTORE=true
    volumes:
      - /root/docker-configs/freepbx/backup:/backup
      - /root/docker-configs/freepbx/recordings:/var/spool/asterisk/monitor

I had to bump the 3306:3306 binding to 3307:3306 because I have a MySQL container already ready on 3306 on this box for the rest of my network and it conflicted.

I created folder volumes on the drive because of how I have my backup plans set and other containers needed an actual folder that i have running so I am not using internal Docker volumes.

So here is what I have happening. Spins up fine. I am able to setup the server, create extensions and have 2 softphones register to those extensions. 

When I try to make a call, the call just drops after 6 seconds with no audio.

In the past when I had this issue, it was usually a NAT issue somewhere so... 
I checked the NAT mode settings on the extensions, and they are set to Yes - (force_rpot,comedia) like i have needed to in the past.
Looked at Settings -> Asterisk SIP Settings - > General Settings:
Allow SIP Guests No
Detect Network Settings Button to get external IP
local networks: Added 10.0.0.0/24 (which is my home network) and 172.0.0.0/24 (the internal network docker created for this stack)

Looked at Settings -> Asterisk SIP Settings - > SIP Legacy Settings:
NAT yes
IP Configuration Static IP
Override External IP is grayed and show my external IP (which it should)

and nothing.... The calls still drop....

Tried to run the container in network_mode: host

the container lasts for about 30 seconds and then tries to restart. More then likely this is because it's trying to spin up it's internal MySQL server on 3306 but this is just a guess...

So not sure where to proceed from here. I would love to get this working since I finally have the hardware to do it and get my existing Home Freepbx off an Rpi I have had it running on to free it up for another project.

Thanks for any assistance....

Jeff

**Comment by flaviostutz** [comment]
It seems like a problem in SDP connection. Try to use network_mode: host in
docker-compose file, but for this you will have to have all ports free in
your host machine (you said you have already a conflict with 3306 port).
Maybe this is due to NAT conflicts in your own network as well.

Hope this helps you!

Flávio Stutz

**Comment by n8acl** [comment]
OK so I took MySQL down and spun up the FPBX container... It stays alive, but without the 8080 port binding I can't get to the admin screen because I am already running a Web Server on 80 on this box....

At this point, I think I am going to move the whole shooting match to a different box I have sitting here and see if I can get it working there in Docker. I will report back once i have that done and seeing what happens...

Thanks for getting back to me! I appreciate it!

**Comment by flaviostutz** [comment]
Great!

**Comment by n8acl** [comment]
OK I moved it to another box and it works. Calls don't drop and audio passes fine. I have it running on network mode host. Looks like it's something with that box and probably the fact I have MySQL running there too. 

Either way.. looks good. I can use this box and install other things on it too so..

Thanks again for your help!

**Comment by flaviostutz** [comment]
Great to here! Please close the issue if it is ok now!

**Comment by n8acl** [comment]
Oh sorry thought i had... :) Done :)
