### ISSUE TITLE
Repo asterisk dosen't exist

### ISSUE THREAD

**Issue by mika-nt28** [flaviostutz/freepbx#3]

**Comment by mika-nt28** [comment]
this repo dosen't exist
http://downloads.asterisk.org/pub/telephony/asterisk/asterisk-15.6.1.tar.gz
i replave by 
http://downloads.asterisk.org/pub/telephony/asterisk/asterisk-15.7.1.tar.gz

**Comment by flaviostutz** [comment]
That’s right. Could you please create a Pull Request?

**Comment by flaviostutz** [comment]
You can use the existing image from Dockerhub at “flaviostutz/freepbx” to overcome this issue. Just remove the “build” tag from the docker-compose
