### ISSUE TITLE
After restarting the docker container, the web interface (port 80) does not open.

### ISSUE THREAD

**Issue by pavelpy** [flaviostutz/freepbx#5]
After restarting the docker container, the web interface (port 80) does not open.

**Comment by techs2resolve** [comment]
mysql not starting container getting terminated

**Comment by flaviostutz** [comment]
Is this happening on current version?

**Comment by flaviostutz** [comment]
@pavelpy feel free to reopen this issue if needed, ok? Maybe in latest version it is not happening... Thanks!
