### ISSUE TITLE
404 error in wget asterisk-15.7.1.tar.gz

### ISSUE THREAD

**Issue by brivadeneira** [flaviostutz/freepbx#9]
Hi there,

the URL `http://downloads.asterisk.org/pub/telephony/asterisk/asterisk-15.7.1.tar.gz` raised an 404 error, correct link is `http://downloads.asterisk.org/pub/telephony/asterisk/asterisk-15.7.2.tar.gz `

Should change code in lines 28, 29 and 30 of Dockerfile's code, like this:

```
	&& wget http://downloads.asterisk.org/pub/telephony/asterisk/asterisk-15.7.2.tar.gz \
	&& tar xfz asterisk-15.7.2.tar.gz \
	&& rm -f asterisk-15.7.2.tar.gz \
```

I will do a pull request.

**Comment by flaviostutz** [comment]
Closed by PR #10
